### ISSUE TITLE
Processing 4.2 pdez files!!

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/thecodingtrain.com#947]
Wow! Processing 4.2 adds the new PDE protocol which allows you to open Processing sketches in the PDE directly from the browser!! We should implement this into the site for all video pages!!

See: https://github.com/processing/processing4/releases/tag/processing-1292-4.2

cc @benfry @SableRaf

Will tackle this here first, but then I can add this to the Nature of Code website as well!

**Comment by SableRaf** [comment]
Quick update to share my reference implementation for the `Open in Processing` button:

https://sableraf.github.io/testURIscheme/

Notice the tooltip that serves as a fallback in case Processing is not installed. 

We could also consider having a separate button for downloading the sketch.

Note: support for `pde://` on Linux is still pending but this Pull Request should solve the issue: https://github.com/processing/processing4/pull/696

**Comment by kfahn22** [comment]
I tried this again.  I was able to open @SableRaf test case, so I used his testURIscheme with my  Persian-rug sketch and it worked. Should we revisit this?

https://kfahn22.github.io/Persian-Rug/

**Comment by dipamsen** [comment]
I still face this https://github.com/processing/processing4/issues/698 issue on Windows, due to which there hadn't been any progress on this.

**Comment by SableRaf** [comment]
> I still face this [processing/processing4#698](https://github.com/processing/processing4/issues/698) issue on Windows, due to which there hadn't been any progress on this earlier.

Do you consider this a blocker? If so we could try looking into it, or if you'd like to submit a fix, I'll be happy to review it. We have just released [Processing 4.3.1](https://github.com/processing/processing4/wiki/Announcing-Processing-4.3.1-(release-candidate)) and resuming development at [processing/processing4](https://github.com/processing/processing4/).

**Comment by SableRaf** [comment]
@stefterv looked into it and [said](https://github.com/processing/processing4/issues/698#issuecomment-2477418942):

> Seems like [an issue with JDK / Javapackager](https://bugs.openjdk.org/browse/JDK-8198549)

So I guess it's unlikely to be solveable in the short term I'm afraid. My take on this is it's still a valuable feature even with this somewhat frustrating limitation.

**Comment by Stefterv** [comment]
A fix is ready to be merged here: https://github.com/processing/processing4/pull/854

**Comment by shiffman** [comment]
Yay! I'd love to have this incorporated into the site if anyone has interest in working on it!

**Comment by kfahn22** [comment]
I have added a pull request with the Coding Challenge Processing example sketches converted to .pdez files [here](https://github.com/CodingTrain/Coding-Challenges/pull/17).

**Comment by SableRaf** [comment]
Hey @shiffman! 

I just wanted to update you on the improvements to the URI schema that we are shipping in 4.4.1 (currently available in Beta) thanks to @Stefterv's amazing work 💙

The new Schema will let you dynamically create `pde://` links. 

It supports Base64 encoding for shorter sketches, and linking to multiple `.pde` or other assets.

This entirely bypasses the need to generate `.pdez` files and opens the door to some really fun possibilities!

See more: https://github.com/processing/processing4/blob/main/SCHEMA.md

**Comment by dipamsen** [comment]
That's very cool, the URL option is very helpful here!
